allall: all

OTHER_HEADERS=dependencies/MCP3008.h
OTHER_OBJS=dependencies/MCP3008.o

LDFLAGS += -L/usr/lib/x86_64-linux-gnu -llgpio -Wl,-rpath,/usr/lib/x86_64-linux-gnu

TARGET=mcp3008Ctrl
include ../../Make/magAOXApp.mk