/* Generated by tests/genTestMacros.py from libMagAOX/app/dev/tests/xwcTestNames.txt. Do not edit. To add a name edit
 * that file and rerun the generator. See tests/genTestMacros.md for how these macros are
 * used by production code and by the unit tests. */


#undef XWCTEST_IF_INDI_CALLBACK_VALIDATION
#ifdef XWCTEST_INDI_CALLBACK_VALIDATION
#define XWCTEST_IF_INDI_CALLBACK_VALIDATION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_INDI_CALLBACK_VALIDATION(line) do {} while(0)
#endif


#undef XWCTEST_IF_TELEMETER_LOGSTART
#ifdef XWCTEST_TELEMETER_LOGSTART
#define XWCTEST_IF_TELEMETER_LOGSTART(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_TELEMETER_LOGSTART(line) do {} while(0)
#endif


