[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "efcControl"
description = "Python INDI device that uses EFC for focal plane wavefront control."
version = "2024.01.17"
dependencies = [
  "xconf",
  "purepyindi2",
]
authors = [
  {name = "Sebastiaan Y. Haffert", email = "shaffert@arizona.edu"},
]

[project.scripts]
efcCtrl = "xapp.efcControl:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["xapp*"]
