
allall: all

NEED_CUDA = no
OTHER_HEADERS =
OTHER_OBJS = recursive_least_squares.o qrd_rls.o ar_controller.o utils.o
TARGET = loPredCtrlAcc
#TARGET = testPredCtrl
#TARGET = testRLS
include ../../Make/magAOXApp.mk
