/* Generated by tests/genTestMacros.py from libMagAOX/modbus/tests/xwcTestNames.txt. Do not edit. To add a name edit
 * that file and rerun the generator. See tests/genTestMacros.md for how these macros are
 * used by production code and by the unit tests. */


#undef XWCTEST_IF_MODBUS_SET_TIMEOUTS_SNDTIMEO_FAIL
#ifdef XWCTEST_MODBUS_SET_TIMEOUTS_SNDTIMEO_FAIL
#define XWCTEST_IF_MODBUS_SET_TIMEOUTS_SNDTIMEO_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MODBUS_SET_TIMEOUTS_SNDTIMEO_FAIL(line) do {} while(0)
#endif


#undef XWCTEST_IF_MODBUS_SEND_PARTIAL
#ifdef XWCTEST_MODBUS_SEND_PARTIAL
#define XWCTEST_IF_MODBUS_SEND_PARTIAL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MODBUS_SEND_PARTIAL(line) do {} while(0)
#endif


