[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xapp-dbIngest"
description = "Per-instrument-computer database ingest virtual device"
version = "2025.12.1"
dependencies = [
  "xconf",
  "purepyindi2",
]
authors = [
  {name = "Joseph D. Long", email = "me@joseph-long.com"},
]

[project.scripts]
dbIngest = "xapp.dbIngest:main"
