ARG BASE_IMAGE=ghcr.io/magao-x/magao-x-setup:gui
FROM ${BASE_IMAGE}
ENV MAGAOX_CONTAINER=1
ENV MAGAOX_ROLE=workstation
ADD . /opt/MagAOX/source/MagAOX
WORKDIR /opt/MagAOX/source/magao-x-setup
USER root
RUN bash -lx first_party/install_MagAOX.sh
WORKDIR /home/xsup
USER xsup
