[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xapp-pythonIndiExample"
description = "Python INDI device implementation example"
version = "2025.11.30"
dependencies = [
  "xconf",
  "purepyindi2",
]
authors = [
  {name = "MagAO-X Team", email = "lynx@magao-x.org"},
]

[project.scripts]
pythonIndiExample = "xapp.pythonIndiExample:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["xapp*"]

[tool.setuptools.package-data]
"xapp.pythonIndiExample" = ["refdata/*"]
