/* Generated by tests/genTestMacros.py from libMagAOX/app/tests/xwcTestNames.txt. Do not edit. To add a name edit
 * that file and rerun the generator. See tests/genTestMacros.md for how these macros are
 * used by production code and by the unit tests. */


#undef XWCTEST_IF_MAGAOXAPP_EXEC_WRONG_USER
#ifdef XWCTEST_MAGAOXAPP_EXEC_WRONG_USER
#define XWCTEST_IF_MAGAOXAPP_EXEC_WRONG_USER(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_EXEC_WRONG_USER(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_EXEC_LOG_START
#ifdef XWCTEST_MAGAOXAPP_EXEC_LOG_START
#define XWCTEST_IF_MAGAOXAPP_EXEC_LOG_START(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_EXEC_LOG_START(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_EXEC_NORM
#ifdef XWCTEST_MAGAOXAPP_EXEC_NORM
#define XWCTEST_IF_MAGAOXAPP_EXEC_NORM(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_EXEC_NORM(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_EXEC_LOG_DEATH
#ifdef XWCTEST_MAGAOXAPP_EXEC_LOG_DEATH
#define XWCTEST_IF_MAGAOXAPP_EXEC_LOG_DEATH(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_EXEC_LOG_DEATH(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_SIGTERMH_ERR
#ifdef XWCTEST_MAGAOXAPP_SIGTERMH_ERR
#define XWCTEST_IF_MAGAOXAPP_SIGTERMH_ERR(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_SIGTERMH_ERR(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_PID_LOCKED
#ifdef XWCTEST_MAGAOXAPP_PID_LOCKED
#define XWCTEST_IF_MAGAOXAPP_PID_LOCKED(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_PID_LOCKED(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_PID_WRITE_FAIL
#ifdef XWCTEST_MAGAOXAPP_PID_WRITE_FAIL
#define XWCTEST_IF_MAGAOXAPP_PID_WRITE_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_PID_WRITE_FAIL(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_PID_UNLOCK_ERR
#ifdef XWCTEST_MAGAOXAPP_PID_UNLOCK_ERR
#define XWCTEST_IF_MAGAOXAPP_PID_UNLOCK_ERR(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_PID_UNLOCK_ERR(line) do {} while(0)
#endif


#undef XWCTEST_IF_INDIDRIVER_CTRL_WRITE_FAIL
#ifdef XWCTEST_INDIDRIVER_CTRL_WRITE_FAIL
#define XWCTEST_IF_INDIDRIVER_CTRL_WRITE_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_INDIDRIVER_CTRL_WRITE_FAIL(line) do {} while(0)
#endif


#undef XWCTEST_IF_INDIDRIVER_OUTGOING_NULL
#ifdef XWCTEST_INDIDRIVER_OUTGOING_NULL
#define XWCTEST_IF_INDIDRIVER_OUTGOING_NULL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_INDIDRIVER_OUTGOING_NULL(line) do {} while(0)
#endif


#undef XWCTEST_IF_INDIDRIVER_SEND_NONSTD_THROW
#ifdef XWCTEST_INDIDRIVER_SEND_NONSTD_THROW
#define XWCTEST_IF_INDIDRIVER_SEND_NONSTD_THROW(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_INDIDRIVER_SEND_NONSTD_THROW(line) do {} while(0)
#endif


#undef XWCTEST_IF_INDIDRIVER_QUIT_AFTER_SEND
#ifdef XWCTEST_INDIDRIVER_QUIT_AFTER_SEND
#define XWCTEST_IF_INDIDRIVER_QUIT_AFTER_SEND(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_INDIDRIVER_QUIT_AFTER_SEND(line) do {} while(0)
#endif


