-- ------------------------telem_cooler--------------------------------
-- DO $$
-- DECLARE keys text;
-- BEGIN
--     DROP VIEW IF EXISTS telem_cooler;
--     SELECT string_agg(distinct format('msg->> %L as %I', jkey, jkey), ', ')
--         INTO keys
--         FROM telem, jsonb_object_keys("msg") as t(jkey)
--         WHERE ec = 'telem_cooler';
--     EXECUTE 'CREATE VIEW telem_cooler AS SELECT device, ts, prio, ec,' ||keys||' FROM telem WHERE ec = ''telem_cooler'' ';
-- END;
-- $$;

-- ---------------------------telem_fxngen------------------------------------
-- DO $$
-- DECLARE keys text;
-- BEGIN
--     DROP VIEW IF EXISTS telem_fxngen;
--     SELECT string_agg(DISTINCT format('msg ->> %L AS %I', jkey, jkey), ', ')
--         INTO keys
--         FROM telem, jsonb_object_keys("msg") as t(jkey)
--         WHERE ec = 'telem_fxngen';
--      EXECUTE 'CREATE VIEW telem_fxngen AS SELECT device, ts, prio, ec,' ||keys||' FROM telemetry WHERE ec = ''telem_fxngen'' ';

-- END;
-- $$;
-- --------------------------telem_observer-------------------------------------
-- DO $$
-- DECLARE keys text;
-- BEGIN    
--     DROP VIEW IF EXISTS telem_observer cascade;
--     SELECT string_agg(DISTINCT format('msg ->> %L as %I', jkey, jkey), ', ')
--         INTO keys
--         FROM telem, jsonb_object_keys("msg") AS t(jkey)
--         WHERE ec = 'telem_observer';
--      EXECUTE 'CREATE VIEW telem_observer AS SELECT device, ts, prio, ec,' ||keys|| ' FROM telem WHERE ec = ''telem_observer''';
-- END;
-- $$;

