#############################################################
#              makefile for a single test                   #
#                                                           #  
# Command:                                                  #
# $ make -f Makefile.one t=<full-path-to-test>              #
#                                                           #
# notes:                                                    #
#   -- normally do not need to edit this file for new tests #
#   -- add conditionals if setuid required, using           #
#      thSetuid_tests as a guide                            #
#   -- can not include precompiled header as tests need to  #
#      define things differently in many cases              #
#                                                           #
#############################################################       


       
SELF_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
include $(SELF_DIR)/../Make/common.mk

# Single-file app name can be supplied as `TARGET=`,
# or `t=` for short
TARGET ?= $(t)

#allow passing of .o, .hpp, or no extension
BASENAME=$(basename $(TARGET))
PATHNAME=$(dir $(TARGET))
OBJNAME = $(PATHNAME)$(notdir $(BASENAME)).o
TESTNAME = $(PATHNAME)$(notdir $(BASENAME))

######################
# setuid             #
######################
#Special handling for tests requiring setuid
ifeq ($(notdir $(BASENAME)),thSetuid_tests)
   SETUID=sudo chown root:root $(TESTNAME) && sudo chmod u+s $(TESTNAME)
endif


all: magaox_git_version.h $(TESTNAME) pcommand

$(TESTNAME): $(OBJNAME) testMain.o
	$(LINK.o) -o $(TESTNAME) testMain.o $(OBJNAME) $(abspath $(SELF_DIR)/../libMagAOX/libMagAOX.a) $(LDFLAGS) $(LDLIBS)
	$(SETUID)

#This just prints the command name, primarily to allow easy access for running a single test
.PHONY: pcommand
pcommand:
	@echo $(TESTNAME)
	
.PHONY: magaox_git_version.h
magaox_git_version.h:
	@gengithead.sh $(abspath $(SELF_DIR)/../) $(SELF_DIR)/../magaox_git_version.h MAGAOX
	
.PHONY: clean
clean:
	@echo cleaning $(TESTNAME)
	@rm -f $(OBJNAME)
	@rm -f $(TESTNAME)
	@rm -f *.binlog
			

.PHONY: realclean
realclean: clean
	@rm -f testMain.o
