###############################################################################
#              makefile for a single test                                     #
#                                                                             #
# Command:                                                                    #
# $ make -f Makefile.one t=<full-path-to-test>                                #
#                                                                             #
# options:                                                                    #
#   TESTLIBS: Can include `TESTLIBS=-l<lib> where lib is a library needed by  #
#             this test, which will be += to LDLIBS.                          #
#                                                                             #
# notes:                                                                      #
#   -- normally do not need to edit this file for new tests                   #
#   -- add conditionals if setuid required, using thSetuid_tests as a guide   #
#   -- can not include precompiled header as tests need to define things      #
#      differently in many cases                                              #
#                                                                             #
###############################################################################



SELF_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
include $(SELF_DIR)/../Make/common.mk

# Single-file app name can be supplied as `TARGET=`,
# or `t=` for short
TARGET ?= $(t)

#allow passing of .o, .hpp, or no extension
BASENAME=$(basename $(TARGET))
PATHNAME=$(dir $(TARGET))
OBJNAME = $(PATHNAME)$(notdir $(BASENAME)).o
TESTNAME = $(PATHNAME)$(notdir $(BASENAME))

# add extra libraries for special cases

ifeq ($(notdir $(TESTNAME)),cursesINDI_test)
	OTHER_HEADERS += cursesTableGrid.hpp
	LDLIBS += -lncurses
else ifeq ($(notdir $(TESTNAME)),logdump_test)
	LDLIBS = -lmxlib -lflatbuffers
else ifeq ($(notdir $(TESTNAME)),logstream_test)
	LDLIBS = -lmxlib -lflatbuffers
else ifeq ($(notdir $(TESTNAME)),logsurgeon_test)
	LDLIBS = -lmxlib -lflatbuffers
else ifeq ($(notdir $(TESTNAME)),xrif2fits_test)
	LDLIBS += -lcfitsio
else ifeq ($(notdir $(TESTNAME)),xrif2shmim_test)
	LDLIBS += -lcfitsio
else ifeq ($(notdir $(TESTNAME)),mzmqClient_test)
	LDLIBS += -lzmq
else ifeq ($(notdir $(TESTNAME)),mzmqServer_test)
	LDLIBS += -lzmq
else ifeq ($(notdir $(TESTNAME)),xInstGraph_test)
    LDLIBS += -linstGraph
else ifeq ($(notdir $(TESTNAME)),fsmNode_test)
    LDLIBS += -linstGraph
else ifeq ($(notdir $(TESTNAME)),indiPropNode_test)
    LDLIBS += -linstGraph
else ifeq ($(notdir $(TESTNAME)),pwrOnOffNode_test)
    LDLIBS += -linstGraph
else ifeq ($(notdir $(TESTNAME)),staticNode_test)
    LDLIBS += -linstGraph
else ifeq ($(notdir $(TESTNAME)),stdMotionNode_test)
    LDLIBS += -linstGraph
else ifeq ($(notdir $(TESTNAME)),xigNode_test)
    LDLIBS += -linstGraph
else ifneq ($(filter $(notdir $(TESTNAME)),ocam2KCtrl_test ocam2KCtrl_lifecycle_test),)
	CPPFLAGS += -I$(PATHNAME)
	CXXFLAGS := $(filter-out -DMAGAOX_NOEDT,$(CXXFLAGS))
	CFLAGS := $(filter-out -DMAGAOX_NOEDT,$(CFLAGS))
	CPPFLAGS := $(filter-out -DMAGAOX_NOEDT,$(CPPFLAGS))
endif

LDLIBS+=$(TESTLIBS)



######################
# setuid             #
######################
#Special handling for tests requiring setuid
ifeq ($(notdir $(TESTNAME)),thSetuid_test)
   SETUID=sudo chown root:root $(TESTNAME) && sudo chmod u+s $(TESTNAME)
endif


all: magaox_git_version.h $(TESTNAME) pcommand

$(TESTNAME): $(OBJNAME) testMain.o
	$(LINK.o) -o $(TESTNAME) testMain.o $(OBJNAME) $(abspath $(SELF_DIR)/../libMagAOX/libMagAOX.a) $(LDFLAGS) $(LDLIBS)
	$(SETUID)

##################################################
# Force, without building all of catch2 using -B
#
# for this to work TARGET must include .cpp
#################################################
force:
	@echo $(TARGET)
	@touch $(TARGET)
	$(MAKE) -f Makefile.one all

#This just prints the command name, primarily to allow easy access for running a single test
.PHONY: pcommand
pcommand:
	@echo "Command to run test: " $(TESTNAME)

.PHONY: magaox_git_version.h
magaox_git_version.h:
	@gengithead.sh $(abspath $(SELF_DIR)/../) $(SELF_DIR)/../magaox_git_version.h MAGAOX

.PHONY: clean
clean:
	@echo cleaning $(TESTNAME)
	@rm -f $(OBJNAME)
	@rm -f $(TESTNAME)
	@rm -f *.binlog


.PHONY: realclean
realclean: clean
	@rm -f testMain.o
