/* Generated by tests/genTestMacros.py from libMagAOX/logger/tests/xwcTestNames.txt. Do not edit. To add a name edit
 * that file and rerun the generator. See tests/genTestMacros.md for how these macros are
 * used by production code and by the unit tests. */


#undef XWCTEST_IF_LOGMAP_AFLTFM_XWCE
#ifdef XWCTEST_LOGMAP_AFLTFM_XWCE
#define XWCTEST_IF_LOGMAP_AFLTFM_XWCE(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_AFLTFM_XWCE(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_AFLTFM_BADALL
#ifdef XWCTEST_LOGMAP_AFLTFM_BADALL
#define XWCTEST_IF_LOGMAP_AFLTFM_BADALL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_AFLTFM_BADALL(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_AFLTFM_EXCEPTION
#ifdef XWCTEST_LOGMAP_AFLTFM_EXCEPTION
#define XWCTEST_IF_LOGMAP_AFLTFM_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_AFLTFM_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_DIREXISTS_ERRC
#ifdef XWCTEST_LOGMAP_LATFM_DIREXISTS_ERRC
#define XWCTEST_IF_LOGMAP_LATFM_DIREXISTS_ERRC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_DIREXISTS_ERRC(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_BADALL1
#ifdef XWCTEST_LOGMAP_LATFM_BADALL1
#define XWCTEST_IF_LOGMAP_LATFM_BADALL1(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_BADALL1(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_BADALL2
#ifdef XWCTEST_LOGMAP_LATFM_BADALL2
#define XWCTEST_IF_LOGMAP_LATFM_BADALL2(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_BADALL2(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_BADALL3
#ifdef XWCTEST_LOGMAP_LATFM_BADALL3
#define XWCTEST_IF_LOGMAP_LATFM_BADALL3(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_BADALL3(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_XWCE4
#ifdef XWCTEST_LOGMAP_LATFM_XWCE4
#define XWCTEST_IF_LOGMAP_LATFM_XWCE4(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_XWCE4(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_XWCE5
#ifdef XWCTEST_LOGMAP_LATFM_XWCE5
#define XWCTEST_IF_LOGMAP_LATFM_XWCE5(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_XWCE5(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_XWCE6
#ifdef XWCTEST_LOGMAP_LATFM_XWCE6
#define XWCTEST_IF_LOGMAP_LATFM_XWCE6(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_XWCE6(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_SIZEERR1
#ifdef XWCTEST_LOGMAP_LATFM_SIZEERR1
#define XWCTEST_IF_LOGMAP_LATFM_SIZEERR1(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_SIZEERR1(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMAP_LATFM_SIZEERR2
#ifdef XWCTEST_LOGMAP_LATFM_SIZEERR2
#define XWCTEST_IF_LOGMAP_LATFM_SIZEERR2(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMAP_LATFM_SIZEERR2(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGINMEMORY_LOADFILE_SHORTREAD
#ifdef XWCTEST_LOGINMEMORY_LOADFILE_SHORTREAD
#define XWCTEST_IF_LOGINMEMORY_LOADFILE_SHORTREAD(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGINMEMORY_LOADFILE_SHORTREAD(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_LOGPATH_BAD_ALLOC
#ifdef XWCTEST_LOGFILERAW_LOGPATH_BAD_ALLOC
#define XWCTEST_IF_LOGFILERAW_LOGPATH_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_LOGPATH_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_LOGPATH_EXCEPTION
#ifdef XWCTEST_LOGFILERAW_LOGPATH_EXCEPTION
#define XWCTEST_IF_LOGFILERAW_LOGPATH_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_LOGPATH_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_LOGNAME_BAD_ALLOC
#ifdef XWCTEST_LOGFILERAW_LOGNAME_BAD_ALLOC
#define XWCTEST_IF_LOGFILERAW_LOGNAME_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_LOGNAME_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_LOGNAME_EXCEPTION
#ifdef XWCTEST_LOGFILERAW_LOGNAME_EXCEPTION
#define XWCTEST_IF_LOGFILERAW_LOGNAME_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_LOGNAME_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_LOGEXT_BAD_ALLOC
#ifdef XWCTEST_LOGFILERAW_LOGEXT_BAD_ALLOC
#define XWCTEST_IF_LOGFILERAW_LOGEXT_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_LOGEXT_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_LOGEXT_EXCEPTION
#ifdef XWCTEST_LOGFILERAW_LOGEXT_EXCEPTION
#define XWCTEST_IF_LOGFILERAW_LOGEXT_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_LOGEXT_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_WRITELOG_FWRITE_FAIL
#ifdef XWCTEST_LOGFILERAW_WRITELOG_FWRITE_FAIL
#define XWCTEST_IF_LOGFILERAW_WRITELOG_FWRITE_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_WRITELOG_FWRITE_FAIL(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_FLUSH_FFLUSH_FAIL
#ifdef XWCTEST_LOGFILERAW_FLUSH_FFLUSH_FAIL
#define XWCTEST_IF_LOGFILERAW_FLUSH_FFLUSH_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_FLUSH_FFLUSH_FAIL(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_CLOSE_FCLOSE_FAIL
#ifdef XWCTEST_LOGFILERAW_CLOSE_FCLOSE_FAIL
#define XWCTEST_IF_LOGFILERAW_CLOSE_FCLOSE_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_CLOSE_FCLOSE_FAIL(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_CREATEFILE_EXCEPTION
#ifdef XWCTEST_LOGFILERAW_CREATEFILE_EXCEPTION
#define XWCTEST_IF_LOGFILERAW_CREATEFILE_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_CREATEFILE_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_CREATEFILE_EXISTS_ERRC
#ifdef XWCTEST_LOGFILERAW_CREATEFILE_EXISTS_ERRC
#define XWCTEST_IF_LOGFILERAW_CREATEFILE_EXISTS_ERRC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_CREATEFILE_EXISTS_ERRC(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGFILERAW_CREATEFILE_FOPEN_FAIL
#ifdef XWCTEST_LOGFILERAW_CREATEFILE_FOPEN_FAIL
#define XWCTEST_IF_LOGFILERAW_CREATEFILE_FOPEN_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGFILERAW_CREATEFILE_FOPEN_FAIL(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMANAGER_LOGTHREADSTART_STD_EXCEPTION
#ifdef XWCTEST_LOGMANAGER_LOGTHREADSTART_STD_EXCEPTION
#define XWCTEST_IF_LOGMANAGER_LOGTHREADSTART_STD_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMANAGER_LOGTHREADSTART_STD_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_LOGMANAGER_LOGTHREADSTART_UNKNOWN_EXCEPTION
#ifdef XWCTEST_LOGMANAGER_LOGTHREADSTART_UNKNOWN_EXCEPTION
#define XWCTEST_IF_LOGMANAGER_LOGTHREADSTART_UNKNOWN_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_LOGMANAGER_LOGTHREADSTART_UNKNOWN_EXCEPTION(line) do {} while(0)
#endif


