#!/bin/bash

#####################################################
## MagAO-X ICC cpuset configuration 
## 
## See https://linux.die.net/man/7/cpuset
##
## Run this as sudo at startup of the system
## Then run icc_procset after starting all loop processes
##
####################################################

# On ICC we have 2x16 = 32 real cores, which maps to 64 cpus
# To see the list: cat /proc/cpuinfo | egrep 'processor|physical id|core id'
# Each row in this table corresponds to a real core, and two logical processors.
#
# processor   physical-id    core-id    processor    physical-id    core-id  
#     0           0            0           32            0            0
#     1           0            1           33            0            1
#     2           0            2           34            0            2
#     3           0            3           35            0            3 
#     4           0            4           36            0            4 
#     5           0            5           37            0            5 
#     6           0            6           38            0            6 
#     7           0            7           39            0            7 
#     8           0            8           40            0            8 
#     9           0            9           41            0            9 
#    10           0            10          42            0            10 
#    11           0            11          43            0            11 
#    12           0            12          44            0            12  
#    13           0            13          45            0            13 
#    14           0            14          46            0            14 
#    15           0            15          47            0            15  
#    16           1            0           48            1            0 
#    17           1            1           49            1            1 
#    18           1            2           50            1            2  
#    19           1            3           51            1            3  
#    20           1            4           52            1            4  
#    21           1            5           53            1            5  
#    22           1            6           54            1            6  
#    23           1            7           55            1            7  
#    24           1            8           56            1            8  
#    25           1            9           57            1            9 
#    26           1            10          58            1            10 
#    27           1            11          59            1            11 
#    28           1            12          60            1            12 
#    29           1            13          61            1            13 
#    30           1            14          61            1            14 
#    31           1            15          63            1            15     

set -euo pipefail

# we will use processors 0-7 and 32-39 as the hyperthread system cpus,
# so we disable processors 40-63. This leaves us 8-31 as single thread processors.

# Disable processors 50-71
for cpu in {40..63}
do
   /bin/echo 0 > /sys/devices/system/cpu/cpu$cpu/online 
done

#Create and mount the root cpuset
if ! mount | grep -q cpuset; then
   mkdir -p /dev/cpuset
   mount -t cpuset cpuset /dev/cpuset
fi
cd /dev/cpuset

#############################
# The system cpuset
#
############################
mkdir -p /dev/cpuset/system
/bin/echo 0-7,32-39 > /dev/cpuset/system/cpuset.cpus
/bin/echo 0-1 > /dev/cpuset/system/cpuset.mems

# Now move all current tasks to system cpuset
# Note that this moves pid=1 (init) so all new process created should live here.
# We use || true to ignore failures, which are caused by stale PIDs
# or attempting to move unmovable kernel threads.
#
while read i; do
   /bin/echo -n $i 2>/dev/null || true
done < tasks > system/tasks

#A guess at how to setup load balancing 
echo 0 > cpuset.sched_load_balance
echo 1 > system/cpuset.sched_load_balance

###############
# Now setup cpusets for the ICC R/T processes
# We have cores 8-31 (24 cores) to use.
# Curently unused: 29-31 (y)  These are created as "spareN"
###############

## NCPC DM

#dm02comb
mkdir -p /dev/cpuset/dm02comb
/bin/echo 8 > /dev/cpuset/dm02comb/cpuset.cpus
/bin/echo 1 > /dev/cpuset/dm02comb/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/dm02comb/cpuset.mems

#ncpc
mkdir -p /dev/cpuset/ncpc
/bin/echo 9 > /dev/cpuset/ncpc/cpuset.cpus
/bin/echo 1 > /dev/cpuset/ncpc/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/ncpc/cpuset.mems

## camlowfs

#camlowfs
mkdir -p /dev/cpuset/camlowfs
/bin/echo 10 > /dev/cpuset/camlowfs/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camlowfs/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camlowfs/cpuset.mems

#camlowfs-sw
mkdir -p /dev/cpuset/camlowfs-sw
/bin/echo 11 > /dev/cpuset/camlowfs-sw/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camlowfs-sw/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camlowfs-sw/cpuset.mems

## camsci1
#camsci1
mkdir -p /dev/cpuset/camsci1
/bin/echo 12 > /dev/cpuset/camsci1/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camsci1/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camsci1/cpuset.mems

#camsci1-sw
mkdir -p /dev/cpuset/camsci1-sw
/bin/echo 13 > /dev/cpuset/camsci1-sw/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camsci1-sw/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camsci1-sw/cpuset.mems

## camsci2
#camsci2
mkdir -p /dev/cpuset/camsci2
/bin/echo 14 > /dev/cpuset/camsci2/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camsci2/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camsci2/cpuset.mems

#camsci2-sw
mkdir -p /dev/cpuset/camsci2-sw
/bin/echo 15 > /dev/cpuset/camsci2-sw/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camsci2-sw/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camsci2-sw/cpuset.mems

## camptip
#camtip
mkdir -p /dev/cpuset/camtip
/bin/echo 16 > /dev/cpuset/camtip/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camtip/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camtip/cpuset.mems

#camtip-sw
mkdir -p /dev/cpuset/camtip-sw
/bin/echo 17 > /dev/cpuset/camtip-sw/cpuset.cpus
/bin/echo 1 > /dev/cpuset/camtip-sw/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/camtip-sw/cpuset.mems

## CACAO

#aolrun 18-24
mkdir -p /dev/cpuset/aol2RT
/bin/echo 18-24 > /dev/cpuset/aol2RT/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/cpuset.mems
/bin/echo 0 > /dev/cpuset/aol2RT/cpuset.sched_load_balance

mkdir -p /dev/cpuset/aol2RT/aol2RT_0
/bin/echo 18 > /dev/cpuset/aol2RT/aol2RT_0/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/aol2RT_0/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/aol2RT_0/cpuset.mems

mkdir -p /dev/cpuset/aol2RT/aol2RT_1
/bin/echo 19 > /dev/cpuset/aol2RT/aol2RT_1/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/aol2RT_1/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/aol2RT_1/cpuset.mems

mkdir -p /dev/cpuset/aol2RT/aol2RT_2
/bin/echo 20 > /dev/cpuset/aol2RT/aol2RT_2/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/aol2RT_2/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/aol2RT_2/cpuset.mems

mkdir -p /dev/cpuset/aol2RT/aol2RT_3
/bin/echo 21 > /dev/cpuset/aol2RT/aol2RT_3/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/aol2RT_3/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/aol2RT_3/cpuset.mems

mkdir -p /dev/cpuset/aol2RT/aol2RT_4
/bin/echo 22 > /dev/cpuset/aol2RT/aol2RT_4/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/aol2RT_4/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/aol2RT_4/cpuset.mems

mkdir -p /dev/cpuset/aol2RT/aol2RT_5
/bin/echo 23 > /dev/cpuset/aol2RT/aol2RT_5/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/aol2RT_5/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/aol2RT_5/cpuset.mems

mkdir -p /dev/cpuset/aol2RT/aol2RT_6
/bin/echo 24 > /dev/cpuset/aol2RT/aol2RT_6/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT/aol2RT_6/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT/aol2RT_6/cpuset.mems

#aol2RT1 -- mvm extrct
mkdir -p /dev/cpuset/aol2RT1
/bin/echo 25 > /dev/cpuset/aol2RT1/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT1/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT1/cpuset.mems

#aol2RT2 -- gpumode2dm
mkdir -p /dev/cpuset/aol2RT2
/bin/echo 26,27 > /dev/cpuset/aol2RT2/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT2/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT2/cpuset.mems

#aol2RT3 -- aol2-ProcessModeCo
mkdir -p /dev/cpuset/aol2RT3
/bin/echo 28 > /dev/cpuset/aol2RT3/cpuset.cpus
/bin/echo 1 > /dev/cpuset/aol2RT3/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/aol2RT3/cpuset.mems

#spare29
mkdir -p /dev/cpuset/spare29
/bin/echo 29 > /dev/cpuset/spare29/cpuset.cpus
/bin/echo 1 > /dev/cpuset/spare29/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/spare29/cpuset.mems

#spare30
mkdir -p /dev/cpuset/spare30
/bin/echo 30 > /dev/cpuset/spare30/cpuset.cpus
/bin/echo 1 > /dev/cpuset/spare30/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/spare30/cpuset.mems

#spare31
mkdir -p /dev/cpuset/spare31
/bin/echo 31 > /dev/cpuset/spare31/cpuset.cpus
/bin/echo 1 > /dev/cpuset/spare31/cpuset.cpu_exclusive
/bin/echo 0-1 > /dev/cpuset/spare31/cpuset.mems

echo "cpusets configured successfully"