#!/bin/bash
#
# Prevent rebalancing IRQs for latency-sensitive hardware interrupts
#
# Install to /usr/local/bin ensuring *only* root can write to the file
# (because it is invoked with root privileges).
#
# Driver names are actually patterns, i.e. enx matches enx2cfda1c6db1a.

#nvidia: any NVIDIA GPU
#enx503eaa0ceeff: ICC camsci1
#enx503eaa0cf4cd: ICC camsci2
#enx98b78501ae64: ICC icc-to-rtc
#pvcamPCIE_0: camflowfs
#pvcamPCIE_1: camllowfs

for driverPattern in nvidia enx503eaa0ceeff enx503eaa0cf4cd enx98b78501ae64 pvcamPCIE_0 pvcamPCIE_1; do
    if [[ $(grep -e "^\s*$2" /proc/interrupts) == *"$driverPattern"* ]]; then
        echo "ban=true"
        exit 0
    fi
done
