#!/bin/bash

#####################################################
## MagAO-X ICC cpuset configuration 
## 
## See https://linux.die.net/man/7/cpuset
##
## Run this as sudo at startup of the system
## Then run icc_procset after starting all loop processes
##
####################################################

source /etc/profile.d/cgroups1_cpuset_mountpoint.sh
cpusetMount=$CGROUPS1_CPUSET_MOUNTPOINT

# On ICC we have 2x16 = 32 real cores, which maps to 64 cpus
# To see the list: cat /proc/cpuinfo | egrep 'processor|physical id|core id'
# Each row in this table corresponds to a real core, and two logical processors.
#
# processor   physical-id    core-id    processor    physical-id    core-id  
#     0           0            0           32            0            0
#     1           0            1           33            0            1
#     2           0            2           34            0            2
#     3           0            3           35            0            3 
#     4           0            4           36            0            4 
#     5           0            5           37            0            5 
#     6           0            6           38            0            6 
#     7           0            7           39            0            7 
#     8           0            8           40            0            8 
#     9           0            9           41            0            9 
#    10           0            10          42            0            10 
#    11           0            11          43            0            11 
#    12           0            12          44            0            12  
#    13           0            13          45            0            13 
#    14           0            14          46            0            14 
#    15           0            15          47            0            15  
#    16           1            0           48            1            0 
#    17           1            1           49            1            1 
#    18           1            2           50            1            2  
#    19           1            3           51            1            3  
#    20           1            4           52            1            4  
#    21           1            5           53            1            5  
#    22           1            6           54            1            6  
#    23           1            7           55            1            7  
#    24           1            8           56            1            8  
#    25           1            9           57            1            9 
#    26           1            10          58            1            10 
#    27           1            11          59            1            11 
#    28           1            12          60            1            12 
#    29           1            13          61            1            13 
#    30           1            14          61            1            14 
#    31           1            15          63            1            15     

set -xeuo pipefail


# we will use processors 0-13 and 32-45 as the hyperthread system cpus,
# so we disable processors 46-63. This leaves us 10-31 as single thread processors.

# Disable processors 46-63
for cpu in {46..63}
do
   /bin/echo 0 > /sys/devices/system/cpu/cpu$cpu/online 
done

cd $cpusetMount

#############################
# The system cpuset
#
############################
mkdir -p $cpusetMount/system
/bin/echo 0-13,32-45 > $cpusetMount/system/cpuset.cpus
/bin/echo 0-1 > $cpusetMount/system/cpuset.mems

# Now move all current tasks to system cpuset
# Note that this moves pid=1 (init) so all new process created should live here.
# We use || true to ignore failures, which are caused by stale PIDs
# or attempting to move unmovable kernel threads.
#
while read i; do
   /bin/echo -n $i 2>/dev/null || true
done < tasks > system/tasks

#A guess at how to setup load balancing 
echo 0 > cpuset.sched_load_balance
echo 1 > system/cpuset.sched_load_balance

###############
# Now setup cpusets for the ICC R/T processes
# We have cores 14-31 (24 cores) to use.
###############

## NCPC DM

#dm02comb
mkdir -p $cpusetMount/dm02comb
/bin/echo 14 > $cpusetMount/dm02comb/cpuset.cpus
/bin/echo 1 > $cpusetMount/dm02comb/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/dm02comb/cpuset.mems

#ncpc
mkdir -p $cpusetMount/ncpc
/bin/echo 15 > $cpusetMount/ncpc/cpuset.cpus
/bin/echo 1 > $cpusetMount/ncpc/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/ncpc/cpuset.mems

## camlowfs

#camlowfs
mkdir -p $cpusetMount/camlowfs
/bin/echo 16 > $cpusetMount/camlowfs/cpuset.cpus
/bin/echo 1 > $cpusetMount/camlowfs/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/camlowfs/cpuset.mems

#camlowfs_sw
mkdir -p $cpusetMount/camlowfs_sw
/bin/echo 17 > $cpusetMount/camlowfs_sw/cpuset.cpus
/bin/echo 1 > $cpusetMount/camlowfs_sw/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/camlowfs_sw/cpuset.mems

## camsci1
#camsci1
mkdir -p $cpusetMount/camsci1
/bin/echo 18 > $cpusetMount/camsci1/cpuset.cpus
/bin/echo 1 > $cpusetMount/camsci1/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/camsci1/cpuset.mems

#camsci1_sw
mkdir -p $cpusetMount/camsci1_sw
/bin/echo 19 > $cpusetMount/camsci1_sw/cpuset.cpus
/bin/echo 1 > $cpusetMount/camsci1_sw/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/camsci1_sw/cpuset.mems

## camsci2
#camsci2
mkdir -p $cpusetMount/camsci2
/bin/echo 20 > $cpusetMount/camsci2/cpuset.cpus
/bin/echo 1 > $cpusetMount/camsci2/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/camsci2/cpuset.mems

#camsci2_sw
mkdir -p $cpusetMount/camsci2_sw
/bin/echo 21 > $cpusetMount/camsci2_sw/cpuset.cpus
/bin/echo 1 > $cpusetMount/camsci2_sw/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/camsci2_sw/cpuset.mems

#spare22
mkdir -p $cpusetMount/spare22
/bin/echo 22 > $cpusetMount/spare22/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare22/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/spare22/cpuset.mems

#spare23
mkdir -p $cpusetMount/spare23
/bin/echo 23 > $cpusetMount/spare23/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare23/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/spare23/cpuset.mems

## CACAO

#acqu_mvm
mkdir -p $cpusetMount/acqu_mvm
/bin/echo 24 > $cpusetMount/acqu_mvm/cpuset.cpus
/bin/echo 1 > $cpusetMount/acqu_mvm/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/acqu_mvm/cpuset.mems

#mfilt
mkdir -p $cpusetMount/mfilt
/bin/echo 25 > $cpusetMount/mfilt/cpuset.cpus
/bin/echo 1 > $cpusetMount/mfilt/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/mfilt/cpuset.mems

#mlat
mkdir -p $cpusetMount/mlat
/bin/echo 26 > $cpusetMount/mlat/cpuset.cpus
/bin/echo 1 > $cpusetMount/mlat/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/mlat/cpuset.mems

#RTmon
mkdir -p $cpusetMount/RTmon
/bin/echo 27 > $cpusetMount/RTmon/cpuset.cpus
/bin/echo 1 > $cpusetMount/RTmon/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/RTmon/cpuset.mems

#spare28
mkdir -p $cpusetMount/spare28
/bin/echo 28 > $cpusetMount/spare28/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare28/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/spare28/cpuset.mems

#spare29
mkdir -p $cpusetMount/spare29
/bin/echo 29 > $cpusetMount/spare29/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare29/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/spare29/cpuset.mems

#spare30
mkdir -p $cpusetMount/spare30
/bin/echo 30 > $cpusetMount/spare30/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare30/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/spare30/cpuset.mems

#spare31
mkdir -p $cpusetMount/spare31
/bin/echo 31 > $cpusetMount/spare31/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare31/cpuset.cpu_exclusive
/bin/echo 0-1 > $cpusetMount/spare31/cpuset.mems

echo "cpusets configured successfully"
