[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "obsLogCtrl"
description = "Active and Historic observations log"
version = "2023.12.21"

authors = [
  {name = "Trevor D. Snedden", email = "tsnedden@arizona.edu"},
]

[project.scripts]
obsLogCtrl = "obsLogCtrl:ObsLogCtrl.console_app"
