#!/bin/bash
#
# Prevent rebalancing IRQs for latency-sensitive hardware interrupts
#
# Install to /usr/local/bin ensuring *only* root can write to the file
# (because it is invoked with root privileges).
#
# Driver names are actually patterns, i.e. enx matches enx2cfda1c6db1a.

for driverPattern in edt enx cp2x72c; do
    if [[ $(grep -e "^\s*$2" /proc/interrupts) == *"$driverPattern"* ]]; then
        echo "ban=true"
        # echo "banned rebalancing of $2 because driver matches $driverPattern" >> /tmp/irqbalance.log
        exit 0
    fi
done
