allall: all

OTHER_HEADERS=dependencies/MCP3208.h
OTHER_OBJS=dependencies/MCP3208.o

LDFLAGS += -L/usr/lib/x86_64-linux-gnu -llgpio -Wl,-rpath,/usr/lib/x86_64-linux-gnu

TARGET=mcp3208Ctrl
include ../../Make/magAOXApp.mk