[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xapp-corAlign"
description = "Python INDI device to align the coronagraph focal plane masks."
version = "2024.01.12"
dependencies = [
  "xconf",
  "purepyindi2",
]
authors = [
  {name = "Sebastiaan Y. Haffert", email = "shaffert@arizona.edu"},
]

[project.scripts]
corAlign = "xapp.corAlign:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["xapp*"]
