#!/usr/bin/env bash

#Script to startup the MagAO-X ICC cacao processes
#
# This script is under version control in the MagAO-X source

cpath=$(pwd)

cd /opt/MagAOX/cacao/ncpc/ncpc-rootdir
cacao-setup ncpc

echo "runstart DMch2disp-02" >> /milk/shm/ncpc_fpsCTRL.fifo

cd $cpath
