#!/usr/bin/env python3
"""
Quick one-off script to subtract a median PSF from FITS files.
"""

from pathlib import Path

import numpy as np
from astropy.io import fits


DEFAULT_INPUT_DIR = Path(
    "/Users/jkueny/data/HR4796_rg_smlyot_20230312_13/raws_rg_smlyot_20230313T043914/camsci1/lite_psflib"
)
INPUT_GLOB = "camsci*_parang.fits"
OUTPUT_SUBDIR = "psf_subtracted"


def load_image_stack(fits_paths):
    """Load FITS image data into a 3D numpy stack."""
    stack = []
    for path in fits_paths:
        with fits.open(path) as hdul:
            stack.append(np.asarray(hdul[0].data, dtype=np.float32))
    return np.stack(stack, axis=0)


def main(input_dir=DEFAULT_INPUT_DIR):
    input_dir = Path(input_dir)
    output_dir = input_dir / OUTPUT_SUBDIR
    output_dir.mkdir(exist_ok=True)

    fits_paths = sorted(input_dir.glob(INPUT_GLOB))
    if not fits_paths:
        raise FileNotFoundError(
            f"No FITS files found in {input_dir} matching pattern '{INPUT_GLOB}'."
        )

    image_stack = load_image_stack(fits_paths)
    median_psf = np.median(image_stack, axis=0).astype(np.float32)

    with fits.open(fits_paths[0]) as hdul_ref:
        psf_header = hdul_ref[0].header.copy()
    psf_header.add_history("Median stack of inputs used as PSF estimate for subtraction.")
    psf_header.add_comment("Generated by do_crude_psf_subtraction.py (psf_estimate_med.fits).")
    psf_path = output_dir / "psf_estimate_med.fits"
    fits.PrimaryHDU(data=median_psf, header=psf_header).writeto(psf_path, overwrite=True)
    print(f"Wrote {psf_path}")

    for path in fits_paths:
        with fits.open(path) as hdul:
            image_data = np.asarray(hdul[0].data, dtype=np.float32)
            subtracted = image_data - median_psf

            output_name = path.name.replace(".fits", "_subtracted.fits")
            output_path = output_dir / output_name

            hdu = fits.PrimaryHDU(data=subtracted, header=hdul[0].header.copy())
            hdu.writeto(output_path, overwrite=True)
            print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
