[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "adcCtrl"
description = "close-loop control for ADCs"
version = "2025.10.15.0"
dependencies = [
  "xconf",
  "purepyindi2",
]
authors = [
  {name = "Katie Twitchell", email = "twitchell@arizona.edu"},
]

[project.scripts]
adcCtrl = "adcCtrl:adcCtrl.console_app"
