
allall: all 

NEED_CUDA = yes
OTHER_HEADERS =
OTHER_OBJS = utils.o new_matrix.o recursive_least_squares.o distributed_ar_controller.o predictive_controller.o
TARGET = hoPredCtrl 
include ../../Make/magAOXApp.mk
