[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xapp-camtipSR"
description = "Instantaneous Strehl Ratio estimate from camtip"
version = "2025.04.09"
dependencies = [
  "xconf",
  "purepyindi2",
]
authors = [
  {name = "Eden McEwen", email = "edenmcewen@arizona.edu"},
]

[project.scripts]
camtipSR = "xapp.camtipSR:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["xapp*"]
