
allall: all 

CXXFLAGS += -DEMULATE_FSM_HARDWARE
OTHER_HEADERS=../CGraphFSMHardwareInterface/CGraphFSMHardwareInterface.hpp
OTHER_OBJS=../CGraphFSMHardwareInterface/CGraphFSMHardwareInterface.o
TARGET=CGFSMHIfpga
include ../../Make/magAOXApp.mk
