/* Generated by tests/genTestMacros.py from libMagAOX/file/tests/xwcTestNames.txt. Do not edit. To add a name edit
 * that file and rerun the generator. See tests/genTestMacros.md for how these macros are
 * used by production code and by the unit tests. */


#undef XWCTEST_IF_STDSUBDIR_CTORSYSDAYS_BAD_ALLOC
#ifdef XWCTEST_STDSUBDIR_CTORSYSDAYS_BAD_ALLOC
#define XWCTEST_IF_STDSUBDIR_CTORSYSDAYS_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_CTORSYSDAYS_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_CTORSYSDAYS_EXCEPTION
#ifdef XWCTEST_STDSUBDIR_CTORSYSDAYS_EXCEPTION
#define XWCTEST_IF_STDSUBDIR_CTORSYSDAYS_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_CTORSYSDAYS_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_YMD_BAD_ALLOC
#ifdef XWCTEST_STDSUBDIR_YMD_BAD_ALLOC
#define XWCTEST_IF_STDSUBDIR_YMD_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_YMD_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_YMD_EXCEPTION
#ifdef XWCTEST_STDSUBDIR_YMD_EXCEPTION
#define XWCTEST_IF_STDSUBDIR_YMD_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_YMD_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_SETPATH_BAD_ALLOC
#ifdef XWCTEST_STDSUBDIR_SETPATH_BAD_ALLOC
#define XWCTEST_IF_STDSUBDIR_SETPATH_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_SETPATH_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_SETPATH_OUT_OF_RANGE
#ifdef XWCTEST_STDSUBDIR_SETPATH_OUT_OF_RANGE
#define XWCTEST_IF_STDSUBDIR_SETPATH_OUT_OF_RANGE(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_SETPATH_OUT_OF_RANGE(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_SETPATH_EXCEPTION
#ifdef XWCTEST_STDSUBDIR_SETPATH_EXCEPTION
#define XWCTEST_IF_STDSUBDIR_SETPATH_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_SETPATH_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_SETPATH_BAD_ALLOC2
#ifdef XWCTEST_STDSUBDIR_SETPATH_BAD_ALLOC2
#define XWCTEST_IF_STDSUBDIR_SETPATH_BAD_ALLOC2(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_SETPATH_BAD_ALLOC2(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_SETPATH_EXCEPTION2
#ifdef XWCTEST_STDSUBDIR_SETPATH_EXCEPTION2
#define XWCTEST_IF_STDSUBDIR_SETPATH_EXCEPTION2(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_SETPATH_EXCEPTION2(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_MAKEPATH_BAD_ALLOC
#ifdef XWCTEST_STDSUBDIR_MAKEPATH_BAD_ALLOC
#define XWCTEST_IF_STDSUBDIR_MAKEPATH_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_MAKEPATH_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_MAKEPATH_FORMAT_ERROR
#ifdef XWCTEST_STDSUBDIR_MAKEPATH_FORMAT_ERROR
#define XWCTEST_IF_STDSUBDIR_MAKEPATH_FORMAT_ERROR(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_MAKEPATH_FORMAT_ERROR(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_MAKEPATH_EXCEPTION
#ifdef XWCTEST_STDSUBDIR_MAKEPATH_EXCEPTION
#define XWCTEST_IF_STDSUBDIR_MAKEPATH_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_MAKEPATH_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_GYMD_BAD_ALLOC
#ifdef XWCTEST_STDSUBDIR_GYMD_BAD_ALLOC
#define XWCTEST_IF_STDSUBDIR_GYMD_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_GYMD_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_GYMD_EXCEPTION
#ifdef XWCTEST_STDSUBDIR_GYMD_EXCEPTION
#define XWCTEST_IF_STDSUBDIR_GYMD_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_GYMD_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_INC_BAD_ALLOC
#ifdef XWCTEST_STDSUBDIR_INC_BAD_ALLOC
#define XWCTEST_IF_STDSUBDIR_INC_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_INC_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_INC_EXCEPTION
#ifdef XWCTEST_STDSUBDIR_INC_EXCEPTION
#define XWCTEST_IF_STDSUBDIR_INC_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_INC_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_PREVFOLL_BAD_ALLOC
#ifdef XWCTEST_STDSUBDIR_PREVFOLL_BAD_ALLOC
#define XWCTEST_IF_STDSUBDIR_PREVFOLL_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_PREVFOLL_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDSUBDIR_PREV_INVAL
#ifdef XWCTEST_STDSUBDIR_PREV_INVAL
#define XWCTEST_IF_STDSUBDIR_PREV_INVAL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDSUBDIR_PREV_INVAL(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDFILENAME_FULLNAME_BAD_ALLOC
#ifdef XWCTEST_STDFILENAME_FULLNAME_BAD_ALLOC
#define XWCTEST_IF_STDFILENAME_FULLNAME_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDFILENAME_FULLNAME_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDFILENAME_FULLNAME_EXCEPTION
#ifdef XWCTEST_STDFILENAME_FULLNAME_EXCEPTION
#define XWCTEST_IF_STDFILENAME_FULLNAME_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDFILENAME_FULLNAME_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDFILENAME_FULLNAME_FS_BAD_ALLOC
#ifdef XWCTEST_STDFILENAME_FULLNAME_FS_BAD_ALLOC
#define XWCTEST_IF_STDFILENAME_FULLNAME_FS_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDFILENAME_FULLNAME_FS_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDFILENAME_FULLNAME_FS_FILESYSTEM_ERROR
#ifdef XWCTEST_STDFILENAME_FULLNAME_FS_FILESYSTEM_ERROR
#define XWCTEST_IF_STDFILENAME_FULLNAME_FS_FILESYSTEM_ERROR(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDFILENAME_FULLNAME_FS_FILESYSTEM_ERROR(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDFILENAME_FULLNAME_FS_EXCEPTION
#ifdef XWCTEST_STDFILENAME_FULLNAME_FS_EXCEPTION
#define XWCTEST_IF_STDFILENAME_FULLNAME_FS_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDFILENAME_FULLNAME_FS_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDFILENAME_FULLNAME_TIMEGM
#ifdef XWCTEST_STDFILENAME_FULLNAME_TIMEGM
#define XWCTEST_IF_STDFILENAME_FULLNAME_TIMEGM(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDFILENAME_FULLNAME_TIMEGM(line) do {} while(0)
#endif


#undef XWCTEST_IF_STDFILENAME_FULLNAME_TIMEGM_OTHER
#ifdef XWCTEST_STDFILENAME_FULLNAME_TIMEGM_OTHER
#define XWCTEST_IF_STDFILENAME_FULLNAME_TIMEGM_OTHER(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_STDFILENAME_FULLNAME_TIMEGM_OTHER(line) do {} while(0)
#endif


#undef XWCTEST_IF_TIMESTAMP_THROW_BAD_ALLOC
#ifdef XWCTEST_TIMESTAMP_THROW_BAD_ALLOC
#define XWCTEST_IF_TIMESTAMP_THROW_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_TIMESTAMP_THROW_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_TIMESTAMP_THROW_FORMAT_ERROR
#ifdef XWCTEST_TIMESTAMP_THROW_FORMAT_ERROR
#define XWCTEST_IF_TIMESTAMP_THROW_FORMAT_ERROR(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_TIMESTAMP_THROW_FORMAT_ERROR(line) do {} while(0)
#endif


#undef XWCTEST_IF_TIMESTAMP_THROW_EXCEPTION
#ifdef XWCTEST_TIMESTAMP_THROW_EXCEPTION
#define XWCTEST_IF_TIMESTAMP_THROW_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_TIMESTAMP_THROW_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_TIMESTAMP_GMTIME_OTHER
#ifdef XWCTEST_TIMESTAMP_GMTIME_OTHER
#define XWCTEST_IF_TIMESTAMP_GMTIME_OTHER(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_TIMESTAMP_GMTIME_OTHER(line) do {} while(0)
#endif


#undef XWCTEST_IF_FILETIMERELPATH_THROW_BAD_ALLOC
#ifdef XWCTEST_FILETIMERELPATH_THROW_BAD_ALLOC
#define XWCTEST_IF_FILETIMERELPATH_THROW_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_FILETIMERELPATH_THROW_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_FILETIMERELPATH_THROW_FORMAT_ERROR
#ifdef XWCTEST_FILETIMERELPATH_THROW_FORMAT_ERROR
#define XWCTEST_IF_FILETIMERELPATH_THROW_FORMAT_ERROR(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_FILETIMERELPATH_THROW_FORMAT_ERROR(line) do {} while(0)
#endif


#undef XWCTEST_IF_FILETIMERELPATH_THROW_EXCEPTION
#ifdef XWCTEST_FILETIMERELPATH_THROW_EXCEPTION
#define XWCTEST_IF_FILETIMERELPATH_THROW_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_FILETIMERELPATH_THROW_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_FILETIMERELPATHSTRING_THROW_BAD_ALLOC
#ifdef XWCTEST_FILETIMERELPATHSTRING_THROW_BAD_ALLOC
#define XWCTEST_IF_FILETIMERELPATHSTRING_THROW_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_FILETIMERELPATHSTRING_THROW_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_FILETIMERELPATHSTRING_THROW_EXCEPTION
#ifdef XWCTEST_FILETIMERELPATHSTRING_THROW_EXCEPTION
#define XWCTEST_IF_FILETIMERELPATHSTRING_THROW_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_FILETIMERELPATHSTRING_THROW_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_PARSETIMESTAMP_THROW_BAD_ALLOC
#ifdef XWCTEST_PARSETIMESTAMP_THROW_BAD_ALLOC
#define XWCTEST_IF_PARSETIMESTAMP_THROW_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_PARSETIMESTAMP_THROW_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_PARSETIMESTAMP_THROW_OUT_OF_RANGE
#ifdef XWCTEST_PARSETIMESTAMP_THROW_OUT_OF_RANGE
#define XWCTEST_IF_PARSETIMESTAMP_THROW_OUT_OF_RANGE(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_PARSETIMESTAMP_THROW_OUT_OF_RANGE(line) do {} while(0)
#endif


#undef XWCTEST_IF_PARSETIMESTAMP_THROW_EXCEPTION
#ifdef XWCTEST_PARSETIMESTAMP_THROW_EXCEPTION
#define XWCTEST_IF_PARSETIMESTAMP_THROW_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_PARSETIMESTAMP_THROW_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_PARSEFILEPATH_THROW_BAD_ALLOC
#ifdef XWCTEST_PARSEFILEPATH_THROW_BAD_ALLOC
#define XWCTEST_IF_PARSEFILEPATH_THROW_BAD_ALLOC(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_PARSEFILEPATH_THROW_BAD_ALLOC(line) do {} while(0)
#endif


#undef XWCTEST_IF_PARSEFILEPATH_THROW_EXCEPTION
#ifdef XWCTEST_PARSEFILEPATH_THROW_EXCEPTION
#define XWCTEST_IF_PARSEFILEPATH_THROW_EXCEPTION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_PARSEFILEPATH_THROW_EXCEPTION(line) do {} while(0)
#endif


#undef XWCTEST_IF_PARSEFILEPATH_THROW_OUT_OF_RANGE
#ifdef XWCTEST_PARSEFILEPATH_THROW_OUT_OF_RANGE
#define XWCTEST_IF_PARSEFILEPATH_THROW_OUT_OF_RANGE(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_PARSEFILEPATH_THROW_OUT_OF_RANGE(line) do {} while(0)
#endif


#undef XWCTEST_IF_PARSEFILEPATH_TOO_SHORT
#ifdef XWCTEST_PARSEFILEPATH_TOO_SHORT
#define XWCTEST_IF_PARSEFILEPATH_TOO_SHORT(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_PARSEFILEPATH_TOO_SHORT(line) do {} while(0)
#endif


