
allall: all

OTHER_HEADERS=xigNodes/xigNode.hpp \
              xigNodes/fsmNode.hpp \
			  xigNodes/indiPropNode.hpp \
			  xigNodes/pwrOnOffNode.hpp \
			  xigNodes/staticNode.hpp \
			  xigNodes/stdMotionNode.hpp

TARGET=instGraph

LDLIBS += -linstGraph

include ../../Make/magAOXUtil.mk

