CXXFLAGS = -lnvinfer -lcudart -L/opt/MagAOX/vendor/TensorRT-10.0.0.6/lib -I/opt/MagAOX/vendor/TensorRT-10.0.0.6/include -I/usr/local/cuda/include -L/usr/local/cuda/lib64/ -Wdeprecated-declarations -g

all : minimal_trt

.PHONY: all