#!/usr/bin/env bash
set -exuo pipefail
if (( $# < 1 )); then
  prefixes=( "/media/backup" "/media/backup2" "/media/backup3" )
else
  prefixes="$@"
fi
for mountpoint in "${prefixes[@]}"; do
    if mount | grep -q "on $mountpoint"; then
        for remote in icc rtc; do
            if ! mount | grep -q "$remote:/data/rawimages on /data/$remote/rawimages"; then
                echo "NFS mount appears not to be active for $remote"
                exit 1
            fi
            
            mkdir -p $mountpoint/$remote
            for dir in rawimages logs telem; do
                rsync -a /data/$remote/$dir/ $mountpoint/$remote/$dir/
            done
            if [[ $remote == "rtc" ]]; then
                # special case to back up cacao data
                rsync -a /data/$remote/cacao/ $mountpoint/$remote/cacao/
            fi
        done
        mkdir -p $mountpoint/aoc
        for dir in rawimages logs telem; do
            rsync -a /data/$dir/ $mountpoint/aoc/$dir/
        done
    fi
done

