#!/bin/bash
set -eo pipefail

#######################################################
# killIndiZombies: kills indiserver zombies
#
#
#######################################################

kill $(ps -elf | awk '{if ($5 == 1){print $4" "$5" "$15}}' | grep MagAOX/drivers | awk '{print $1}') 
