#!/bin/bash

#########################################################
# apply a LOWFS calibration and reload CACAO
#########################################################

echo 'Applying Calibration' $1

echo "runstop mvalC2dm-2" >> /milk/shm/ncpc_fpsCTRL.fifo
echo "confstop mvalC2dm-2" >> /milk/shm/ncpc_fpsCTRL.fifo
echo "runstop mfilt-2" >> /milk/shm/ncpc_fpsCTRL.fifo
echo "confstop mfilt-2" >> /milk/shm/ncpc_fpsCTRL.fifo
echo "runstop wfs2cmodeval-2" >> /milk/shm/ncpc_fpsCTRL.fifo
echo "confstop wfs2cmodeval-2" >> /milk/shm/ncpc_fpsCTRL.fifo

cd /opt/MagAOX/cacao/ncpc/ncpc001

cmd='cacao-calib-apply '$1
$cmd

sleep 1
echo "confstart wfs2cmodeval-2" >> /milk/shm/ncpc_fpsCTRL.fifo
sleep 1
echo "runstart wfs2cmodeval-2" >> /milk/shm/ncpc_fpsCTRL.fifo
sleep 1
echo "confstart mfilt-2" >> /milk/shm/ncpc_fpsCTRL.fifo
sleep 1
echo "runstart mfilt-2" >> /milk/shm/ncpc_fpsCTRL.fifo
sleep 1
echo "confstart mvalC2dm-2" >> /milk/shm/ncpc_fpsCTRL.fifo
sleep 1
echo "runstart mvalC2dm-2" >> /milk/shm/ncpc_fpsCTRL.fifo

milk <<EOF
readshmim aol2_wfsref
cpsh aol2_wfsref aol2_wfsrefc
exitCLI
EOF


