#!/bin/bash
set -e
# Query for seeing measurements from DIMM and Magellans
# Joseph Long - 2019B
# Database assistance (and access for exao1) by Gabriel Prieto

# Don't run except at LCO
if ! nmcli con show --active | grep www-lco &> /dev/null; then
    exit
fi

# DIMM columns
# tm - timestamp
# se - FWHM
# el - elevation
export dimm=$(mysql \
    --raw \
    --batch \
    --connect-timeout=1 \
    --host clima.lco.cl \
    --user read_data_ao \
    --execute "select tm as datetime, se as fwhm, el as elevation from dimm_data where un = 0 order by tm desc limit 1" \
    weather)
echo -e "dimm\n$dimm"
echo "$dimm" > /tmp/dimm.tsv

# Magellan Baade and Clay columns
# tm - timestamp
# fw - fwhm
# el - elevation
export mag1=$(mysql \
    --raw \
    --batch \
    --connect-timeout=1 \
    --host clima.lco.cl \
    --user read_data_ao \
    --execute "select tm as datetime, fw as fwhm, el as elevation from magellan_data where un = 0 order by tm desc limit 1" \
    weather)
echo -e "mag1\n$mag1"
echo "$mag1" > /tmp/mag1.tsv
export mag2=$(mysql \
    --raw \
    --batch \
    --connect-timeout=1 \
    --host clima.lco.cl \
    --user read_data_ao \
    --execute "select tm as datetime, fw as fwhm, el as elevation from magellan_data where un = 1 order by tm desc limit 1" \
    weather)
echo -e "mag2\n$mag2"
echo "$mag2" > /tmp/mag2.tsv