#!/bin/bash
#####################################################
## MagAO-X RTC process to cpuset  
## 
## See https://linux.die.net/man/7/cpuset
##
## Run this as sudo after starting all loop processes.
## Must first have run rtc_cpuset.bash at system startup.
##
####################################################


######################
## camwfs framegrabber
######################
pidlist=$( getINDI camwfs.th-framegrabber.pid | xargs echo | sed 's/.*=//g')
echo "camwfs f.g.            : $pidlist"
/bin/echo $pidlist > /dev/cpuset/camwfs/tasks
echo ""

######################
## Woofer dmcomb
######################
pidlist=$( pgrep DMcomb-000000.r | xargs echo | sed 's/ /,/g' )
echo "DMcomb 0            : $pidlist"
/bin/echo $pidlist > /dev/cpuset/dm00comb/tasks
echo ""

######################
## Woofer shmimMonitor
######################
pidlist=$( getINDI dmwoofer.th-shmimMonitor.pid | xargs echo | sed 's/.*=//g')
echo "woofer s.m.            : $pidlist"
/bin/echo $pidlist > /dev/cpuset/woofer/tasks
echo ""

######################
## Tweeter dmcomb
######################
pidlist=$( pgrep DMcomb-000001.r | xargs echo | sed 's/ /,/g' )
echo "DMcomb 1            : $pidlist"
/bin/echo $pidlist > /dev/cpuset/dm01comb/tasks
echo ""

######################
## Tweeter shmimMonitor
######################
pidlist=$( getINDI dmtweeter.th-shmimMonitor.pid | xargs echo | sed 's/.*=//g')
echo "tweeter s.m.            : $pidlist"
/bin/echo $pidlist > /dev/cpuset/woofer/tasks
echo ""

######################
## T2W offloader shmimMonitor
######################
pidlist=$( getINDI t2wOffloader.th-shmimMonitor.pid | xargs echo | sed 's/.*=//g')
echo "t2w offloader s.m.            : $pidlist"
/bin/echo $pidlist > /dev/cpuset/woofer/tasks
echo ""


pidlist=$( pgrep aol1run | xargs echo | sed 's/ /,/g' )
echo "aol1 (master)       : $pidlist"
aolPID="$pidlist"
echo ""

pidlist=$( ls /proc/$aolPID/task/ )
echo "aol1 (full) :"
echo "$pidlist"

let i=0
for pid in $pidlist
do
   /bin/echo $pid > /dev/cpuset/aol1RT/aol1RT_${i}/tasks
   let i=i+1
done
echo ""



pidlist=$( pgrep aol1mexwfs | xargs echo | sed 's/ /,/g' )
echo "cudaMVMextract aol1 : $pidlist"
aolPID="$pidlist"
/bin/echo $pidlist > /dev/cpuset/aol1RT1/tasks
echo ""


pidlist=$( pgrep aol1dmfw | xargs echo | sed 's/ /,/g' )
echo "aol1 GPUmodes2dm    : $pidlist"
aolPID="$pidlist"
echo ""
pidlist=$( ls /proc/$aolPID/task/ )
echo "aol1 GPUmodes2dm (full) :"
echo "$pidlist"
for pid in $pidlist
do
   /bin/echo $pid > /dev/cpuset/aol1RT2/tasks
done
echo ""

pidlist=$( pgrep aol1meol | xargs echo | sed 's/ /,/g' )
echo "aol1meol         : $pidlist"
/bin/echo $pidlist > /dev/cpuset/aol1RT3/tasks
echo ""

