#################################################
#
# Common path and make variable definitions for a MagAO-X build.
#
# This file defines the typical values and manages O/S detection, etc.
# To change these create a local/common.mk and set the values you want to change
# in that directory.
#
# NOTE: do not edit this file, as it will show as a git repo modification.
#
###################################################

SELF_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
-include $(SELF_DIR)/../local/common.mk
include $(SELF_DIR)/config.mk

# Ensure a C++ compiler is defined for the check
CXX ?= g++

# Probe compiler identification string (lowercased)
CXX_ID := $(shell $(CXX) --version 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)

# If output mentions "gcc" and does NOT mention "clang" then treat as GCC and enforce version
ifneq (,$(findstring gcc,$(CXX_ID)))
ifneq (,$(findstring clang,$(CXX_ID)))
  # clang (or clang-compatible) detected — allow (clang defines gcc compatibility macros)
else
  # Attempt to extract GCC major version
  GCC_MAJOR := $(shell $(CXX) -dumpfullversion -dumpversion 2>/dev/null | sed 's/^\([0-9]\+\).*/\1/' || true)
  ifeq ($(GCC_MAJOR),)
    GCC_MAJOR := $(shell echo "$(CXX_ID)" | sed -n 's/.*gcc[^0-9]*\([0-9]\+\).*/\1/p' || true)
  endif

  ifeq ($(GCC_MAJOR),)
    $(warning Could not determine GCC major version for $(CXX); proceeding without strict check)
  else
    # Error out if GCC major version is less than 14
    ifeq ($(shell [ $(GCC_MAJOR) -lt 14 ] 2>/dev/null && echo yes || echo no),yes)
      $(error Detected GCC $(GCC_MAJOR); GCC >= 14 is required)
    endif
  endif
endif
endif

### Set up what libs to require based on the MAGAOX_ROLE
EDT ?= false
ifeq ($(MAGAOX_ROLE),RTC)
  EDT = true
endif

ifeq ($(COVERAGE),1)
  CFLAGS += --coverage
  CXXFLAGS += --coverage
endif

ifeq ($(MAGAOX_ROLE),SS)
  CXXFLAGS += -DXWC_SIM_MODE
endif

LIB_PATH ?= $(PREFIX)/lib
INCLUDE_PATH ?= $(PREFIX)/include
LIB_SOFA ?= $(LIB_PATH)/libsofa_c.a

INCLUDES += -I$(INCLUDE_PATH) -I$(abspath $(SELF_DIR)/../flatlogs/include)
INCLUDES += $(shell pkg-config --cflags eigen3)

###################################################
# import mxlib configuration
###################################################
MXLIB_CFLAGS=$(shell pkg-config --cflags mxlib)
MXLIB_LIBS=$(shell pkg-config --libs mxlib)

CFLAGS+=$(MXLIB_CFLAGS)
CXXFLAGS+=$(MXLIB_CFLAGS)

########################################
## Optimize Flags
#######################################

#note: OPTIMIZE gets appended at very end, so will override settings in MXLIB_CFLAGS

OPTIMIZE ?= -ffast-math

ifeq ($(COVERAGE),1)
  OPTIMIZE += -O0
else
  OPTIMIZE += -O3
endif

ifeq ($(DEBUG),1)
  CXXFLAGS += -DDEBUG
  OPTIMIZE += -O0 -g
endif

########################################
## Libraries
#######################################

EXTRA_LDFLAGS ?=

#the required librarires
EXTRA_LDLIBS ?=  $(MXLIB_LIBS) \
                 -ludev \
                 -lxrif \
                 $(abspath $(SELF_DIR)/../libs/libtelnet/libtelnet.a) \
                 $(abspath $(SELF_DIR)/../INDI/libcommon/libcommon.a) \
                 $(abspath $(SELF_DIR)/../INDI/liblilxml/liblilxml.a)

### EDT
ifneq ($(EDT),false)
   EDT_PATH=/opt/EDTpdv
   EDT_INCLUDES=-I$(EDT_PATH)
   EDT_LIBS = -L/opt/EDTpdv -lpdv -lpthread -lm -ldl

   INCLUDES += $(EDT_INCLUDES)
   EXTRA_LDLIBS += $(EDT_LIBS)
else
   CXXFLAGS+= -DMAGAOX_NOEDT
endif

########################################
## Compilation and linking
#######################################

LDLIBS += $(EXTRA_LDLIBS)
LDFLAGS += $(EXTRA_LDFLAGS)

ifeq ($(COVERAGE),1)
  LDFLAGS += --coverage
endif

#Hard-code the paths to system libraries so setuid works
LDLIBRPATH := $(shell echo $$LD_LIBRARY_PATH | sed 's/::/:/g' |  sed 's/:/ -Wl,-rpath,/g')
LDLIBS += -Wl,-rpath,$(LDLIBRPATH)

CSTD ?= -std=c99

CFLAGS += $(CSTD) -fPIC $(INCLUDES) $(OPTIMIZE)
CXXFLAGS += $(CXXSTD) -Wall -Wextra -fPIC $(INCLUDES) $(OPTIMIZE)

#This is needed to force use of g++ for linking
LINK.o = $(LINK.cc)

#Create an implicit rule for pre-compiled headers
%.hpp.gch: %.hpp
	$(CXX) $(CXXFLAGS) -c $<
