#################################################
#
#  Configuration settings for a MagAO-X build.
# 
# This file defines the default values.  To change these
# Create a local/config.mk and set the values you want to change
# in that directory.
# 
# NOTE: do not edit this file, as it will show as a git repo modification.
#
###################################################

SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
-include $(SELF_DIR)/../local/config.mk

PREFIX?=/opt/MagAOX

BIN_PATH?=$(PREFIX)/bin
DRIVER_PATH?=$(PREFIX)/drivers
FIFO_PATH?=$(PREFIX)/drivers/fifos
