#################################################
#
#  Configuration settings for a MagAO-X build.
#
# This file defines the default values.  To change these
# Create a local/config.mk and set the values you want to change
# in that directory.
#
# NOTE: do not edit this file, as it will show as a git repo modification.
#
###################################################

SELF_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
-include $(SELF_DIR)/../local/config.mk

MAGAOX_PREFIX?=/opt/MagAOX
PREFIX?=/usr/local

BIN_PATH?=$(MAGAOX_PREFIX)/bin
DRIVER_PATH?=$(MAGAOX_PREFIX)/drivers
FIFO_PATH?=$(MAGAOX_PREFIX)/drivers/fifos
