#!/bin/bash
#
# Prevent rebalancing IRQs for latency-sensitive hardware interrupts
#
# Install to /usr/local/bin ensuring *only* root can write to the file
# (because it is invoked with root privileges).
#
# Driver names are actually patterns, i.e. enx matches enx2cfda1c6db1a.

#edt: any EDT gramegrabber
#nvidia: any NVIDIA GPU
#enx98b78501aebc: shmimTCP NIC
#cp2x72c: ALPAO -> dmwoofer

for driverPattern in edt nvidia enx98b78501aebc cp2x72c; do
    if [[ $(grep -e "^\s*$2" /proc/interrupts) == *"$driverPattern"* ]]; then
        echo "ban=true"
        exit 0
    fi
done
