#!/bin/bash

#####################################################
## MagAO-X RTC cpuset configuration 
## 
## See https://linux.die.net/man/7/cpuset
##
## Run this as sudo at startup of the system
## Then run rtc_procset after starting all loop processes
##
####################################################

source /etc/profile.d/cgroups1_cpuset_mountpoint.sh
cpusetMount=$CGROUPS1_CPUSET_MOUNTPOINT

# RTC w/ AMD Threadripper 64 core / 128 threads

set -xeuo pipefail

# we will use processors 0-31 and 64-95 as the hyperthread system cpus (32 cores, 64 threads),
# so we disable processors 96-127. This leaves us 32-63 (32) as single thread r/t processors.

#enable everything first just to start from a known state
for cpu in {1..127}
do
   /bin/echo 1 > /sys/devices/system/cpu/cpu$cpu/online
done

# Disable processors 96-127, the hardware threads
for cpu in {96..127}
do
   /bin/echo 0 > /sys/devices/system/cpu/cpu$cpu/online 
done

cd $cpusetMount

#############################
# The system cpuset
#
############################
mkdir -p $cpusetMount/system
/bin/echo 0-31,64-95 > $cpusetMount/system/cpuset.cpus
/bin/echo 0 > $cpusetMount/system/cpuset.mems

# Now move all current tasks to system cpuset
# Note that this moves pid=1 (init) so all new process created should live here.
# We use || true to ignore failures, which are caused by stale PIDs
# or attempting to move unmovable kernel threads.
#
while read i; do
   /bin/echo -n $i 2>/dev/null || true
done < tasks > system/tasks

#A guess at how to setup load balancing 
echo 0 > cpuset.sched_load_balance
echo 1 > system/cpuset.sched_load_balance

###############
# Now setup cpusets for the RTC R/T processes
###############


#camwfs_sw
mkdir -p $cpusetMount/camwfs_sw
/bin/echo 32 > $cpusetMount/camwfs_sw/cpuset.cpus
/bin/echo 1 > $cpusetMount/camwfs_sw/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/camwfs_sw/cpuset.mems

#camwfs
mkdir -p $cpusetMount/camwfs
/bin/echo 33 > $cpusetMount/camwfs/cpuset.cpus
/bin/echo 1 > $cpusetMount/camwfs/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/camwfs/cpuset.mems

#camwfs2
mkdir -p $cpusetMount/camwfs2
/bin/echo 34 > $cpusetMount/camwfs2/cpuset.cpus
/bin/echo 1 > $cpusetMount/camwfs2/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/camwfs2/cpuset.mems

#spare35
mkdir -p $cpusetMount/spare35
/bin/echo 35 > $cpusetMount/spare35/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare35/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare35/cpuset.mems

#spare36
mkdir -p $cpusetMount/spare36
/bin/echo 36 > $cpusetMount/spare36/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare36/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare36/cpuset.mems

#dm00comb (woofer)
mkdir -p $cpusetMount/dm00comb
/bin/echo 37 > $cpusetMount/dm00comb/cpuset.cpus
/bin/echo 1 > $cpusetMount/dm00comb/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/dm00comb/cpuset.mems

#woofer
mkdir -p $cpusetMount/woofer
/bin/echo 38 > $cpusetMount/woofer/cpuset.cpus
/bin/echo 1 > $cpusetMount/woofer/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/woofer/cpuset.mems

#dm01comb
mkdir -p $cpusetMount/dm01comb
/bin/echo 39 > $cpusetMount/dm01comb/cpuset.cpus
/bin/echo 1 > $cpusetMount/dm01comb/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/dm01comb/cpuset.mems

#tweeter
mkdir -p $cpusetMount/tweeter
/bin/echo 40 > $cpusetMount/tweeter/cpuset.cpus
/bin/echo 1 > $cpusetMount/tweeter/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/tweeter/cpuset.mems

#t2w offload process 
mkdir -p $cpusetMount/t2w
/bin/echo 41 > $cpusetMount/t2w/cpuset.cpus
/bin/echo 1 > $cpusetMount/t2w/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/t2w/cpuset.mems

#spare42
mkdir -p $cpusetMount/spare42
/bin/echo 42 > $cpusetMount/spare42/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare42/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare42/cpuset.mems

#spare43
mkdir -p $cpusetMount/spare43
/bin/echo 43 > $cpusetMount/spare43/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare43/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare43/cpuset.mems

#spare44
mkdir -p $cpusetMount/spare44
/bin/echo 44 > $cpusetMount/spare44/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare44/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare44/cpuset.mems

#acqu_mvm
mkdir -p $cpusetMount/acqu_mvm
/bin/echo 45 > $cpusetMount/acqu_mvm/cpuset.cpus
/bin/echo 1 > $cpusetMount/acqu_mvm/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/acqu_mvm/cpuset.mems

#mfilt
mkdir -p $cpusetMount/mfilt
/bin/echo 46 > $cpusetMount/mfilt/cpuset.cpus
/bin/echo 1 > $cpusetMount/mfilt/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/mfilt/cpuset.mems

#tweeterSpeck
mkdir -p $cpusetMount/tweeterSpeck
/bin/echo 47 > $cpusetMount/tweeterSpeck/cpuset.cpus
/bin/echo 1 > $cpusetMount/tweeterSpeck/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/tweeterSpeck/cpuset.mems

#mlat
mkdir -p $cpusetMount/mlat
/bin/echo 48 > $cpusetMount/mlat/cpuset.cpus
/bin/echo 1 > $cpusetMount/mlat/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/mlat/cpuset.mems

#RTmon
mkdir -p $cpusetMount/RTmon
/bin/echo 49 > $cpusetMount/RTmon/cpuset.cpus
/bin/echo 1 > $cpusetMount/RTmon/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/RTmon/cpuset.mems

#spare50
mkdir -p $cpusetMount/spare50
/bin/echo 50 > $cpusetMount/spare50/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare50/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare50/cpuset.mems

#spare51
mkdir -p $cpusetMount/spare51
/bin/echo 51 > $cpusetMount/spare51/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare51/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare51/cpuset.mems

#spare52
mkdir -p $cpusetMount/spare52
/bin/echo 52 > $cpusetMount/spare52/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare52/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare52/cpuset.mems

#spare53
mkdir -p $cpusetMount/spare53
/bin/echo 53 > $cpusetMount/spare53/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare53/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare53/cpuset.mems

#camtip
mkdir -p $cpusetMount/camtip
/bin/echo 54 > $cpusetMount/camtip/cpuset.cpus
/bin/echo 1 > $cpusetMount/camtip/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/camtip/cpuset.mems

#camtip_sw
mkdir -p $cpusetMount/camtip_sw
/bin/echo 55 > $cpusetMount/camtip_sw/cpuset.cpus
/bin/echo 1 > $cpusetMount/camtip_sw/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/camtip_sw/cpuset.mems

#camacq
mkdir -p $cpusetMount/camacq
/bin/echo 56 > $cpusetMount/camacq/cpuset.cpus
/bin/echo 1 > $cpusetMount/camacq/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/camacq/cpuset.mems

#camacq_sw
mkdir -p $cpusetMount/camacq_sw
/bin/echo 57 > $cpusetMount/camacq_sw/cpuset.cpus
/bin/echo 1 > $cpusetMount/camacq_sw/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/camacq_sw/cpuset.mems

#shmimTCP
mkdir -p $cpusetMount/shmimTCP
/bin/echo 58 > $cpusetMount/shmimTCP/cpuset.cpus
/bin/echo 1 > $cpusetMount/shmimTCP/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/shmimTCP/cpuset.mems

#spare59
mkdir -p $cpusetMount/spare59
/bin/echo 59 > $cpusetMount/spare59/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare59/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare59/cpuset.mems

#spare60
mkdir -p $cpusetMount/spare60
/bin/echo 60 > $cpusetMount/spare60/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare60/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare60/cpuset.mems

#spare61
mkdir -p $cpusetMount/spare61
/bin/echo 61 > $cpusetMount/spare61/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare61/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare61/cpuset.mems

#spare62
mkdir -p $cpusetMount/spare62
/bin/echo 62 > $cpusetMount/spare62/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare62/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare62/cpuset.mems

#spare63
mkdir -p $cpusetMount/spare63
/bin/echo 63 > $cpusetMount/spare63/cpuset.cpus
/bin/echo 1 > $cpusetMount/spare63/cpuset.cpu_exclusive
/bin/echo 0 > $cpusetMount/spare63/cpuset.mems


echo "cpusets configured successfully"
