channels:
  - conda-forge
dependencies:
  - astropy
  # Note: omission of jupyter and use of matplotlib-base prevents dependency on qt
  - jupyterlab
  - notebook
  - ipython
  - ipywidgets
  - matplotlib-base
  - numpy
  - scipy
  - numexpr
  - Pillow
  - scikit-image
  - pip
  - nb_conda_kernels
  - pytest
  - pybind11
  - psutil
  - cupy
  - line_profiler
  - pyserial
  # hcipy deps available in conda
  - asdf
  - pyyaml
  - imageio
  - xxhash
  # for cacao
  - pybind11
  # for xtelemdb
  - psycopg
  - python-duckdb

  - pip:
      - hcipy
      - poppy
