
allall: all

OTHER_HEADERS=orcaUtils.hpp
TARGET=orcaCtrl

LDLIBS += -ldcamapi

include ../../Make/magAOXApp.mk


# allall: all

# TARGET=orcaCtrl

# EDT=true
# EDT_PATH=/opt/EDTpdv

# EDT_INCLUDES=-I$(EDT_PATH)
# EDT_LIBS = -L/opt/EDTpdv -lpdv -lpthread -lm -ldl

# INCLUDES += $(EDT_INCLUDES)
# LDLIBS += $(EDT_LIBS)

# include ../../Make/magAOXApp.mk
