
allall: all

OTHER_HEADERS=xigNodes/xigNode.hpp \
              xigNodes/fsmNode.hpp \
			  xigNodes/indiPropNode.hpp \
			  xigNodes/pwrOnOffNode.hpp \
			  xigNodes/staticNode.hpp \
			  xigNodes/stdMotionNode.hpp

TARGET=xInstGraph

LDLIBS += -linstGraph

include ../../Make/magAOXApp.mk

