name: Container build
on:
  push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: magao-x/magaox
  BASE_IMAGE_NAME: magao-x/magao-x-setup
jobs:
  build-and-push-rocky-x86_64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker (full)
        id: meta_full
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image (no GUIs)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/dev' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cli
          labels: ${{ steps.meta_full.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:cli
            MAGAOX_ROLE=container
      - name: Build and push Docker image (GUIs)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/dev' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:gui
          labels: ${{ steps.meta_full.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:gui
            MAGAOX_ROLE=workstation
