name: Coverage
on:
  push:
      branches:
        - '**' # Any branch
        - '!jrmales/logdirs' #this requires work to move gcc to 14
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joseph-long/magao-x-setup-develop:main
      options: --user root
    steps:
      - name: Install Packages
        run: dnf install -y lcov make libusb-devel libusbx-devel
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory "$(pwd)"
      - name: Generate Coverage
        run: |
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          pkg-config --modversion openblas
          make coverage_clean
          make coverage
          cd tests
          make coverage
          lcov --directory . --zerocounters
          chmod +x testMagAOX.bash
          bash -l testMagAOX.bash
          cd ..
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info "*/tests/*" "/usr/*" "/sys/*" "/tty/*" --output-file coverage_filtered.info
          genhtml coverage_filtered.info --output-directory coverage_report --title "MagAOX" --hierarchical --merge-aliases --suppress-aliases --filter function --demangle-cpp --css-file tests/coverage/gcov.css
      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: coverage_report/
      - name: When on dev, add SSH key
        if: github.ref == 'refs/heads/dev'
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            echo "xwcl.science ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqGanUWS9Wb34oCHCDX2xqhlCstMTN9c0oFoKJkYtZ3" >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.DEPLOY_GARY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add /home/runner/.ssh/github_actions
      - name: When on dev, sync to magao-x.org
        if: github.ref == 'refs/heads/dev'
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            rsync -e 'ssh -o "UserKnownHostsFile /home/runner/.ssh/known_hosts"' -rz --delete coverage_report/ gary@xwcl.science:/srv/www/main/docs/coverage/
